locale: "ko-KR"
title: "DevHwan's Blog"
url: "https://devhwan.github.io"
dsecription: "DevHwan's Blog"

remote_theme: minimal-mistakes
minimal_mistakes_skin: "default"

encoding: "utf-8"

github:
  is_project_page: false
  
